# Generated by Django 4.2.4 on 2023-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bank',
            field=models.ManyToManyField(to='general.card'),
        ),
    ]
