# Generated by Django 4.2.4 on 2023-08-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_category_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
