# Generated by Django 4.2.4 on 2023-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_guestcategoryprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestCategoryPrice',
        ),
    ]
