# Generated by Django 4.2.4 on 2023-08-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_delete_guestcategoryprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bank',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
